--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/Trashcan
build-by-default: true
branches:
- master
projects:
  Trashcan:
    path: ""
    icon: "/assets/icon.png"
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: pm5
        version: ^4.6.5
...
